
[files]
text_file = "../../../data/raw_text.txt"
opm_file = "../../../data/pump_opl.html"
entity_file = "../../../data/entities.csv"

output_health_status_file = "../../../data/output_health_status.csv"
output_causal_effect_file = "../../../data/output_causal_effect.csv"
