
[files]
text_file = "../../../data/raw_text.txt"
entity_file = "../../../data/entities.csv"
output_health_status_file = "../../../general_tests/excavator/excavator_output_health_status.csv"
output_causal_effect_file = "../../../general_tests/excavator/excavator_output_causal_effect.csv"
