
[files]
text_file = "../../../general_tests/excavator/excavator.txt"
#text_file = "../../../general_tests/excavator/excavator_shortlist.txt"
entity_file = "../../../general_tests/excavator/excavator_entities.csv"

output_health_status_file = "../../../general_tests/excavator/excavator_output_health_status.csv"
output_causal_effect_file = "../../../general_tests/excavator/excavator_output_causal_effect.csv"
