
[files]
text_file = "../../../data/cws_data.txt"
opm_file = "../../../models/opmModels/CWS.html"
entity_file = "../../../data/entities.csv"

output_health_status_file = "../../../data/output_health_status.csv"
output_causal_effect_file = "../../../data/output_causal_effect.csv"
