
[files]
text_file = "../../../general_tests/LER/raw_extract_from_pdf.txt"
entity_file = "../../../general_tests/LER/entity.csv"

output_health_status_file = "../../../general_tests/LER/output_health_status.csv"
output_causal_effect_file = "../../../general_tests/LER/output_causal_effect.csv"

output_status_file = "../../../general_tests/LER/output_status.csv"
output_relation_file = "../../../general_tests/LER/output_relation.csv"
