
[files]
text_file = ""
entity_file = ""
cause_effect_keywords_file = "../../../data/cause_effect_keywords.csv"
conjecture_keywords_file = "../../../data/conjecture_keywords.csv"

status_keywords_file.all = "../../../data/health_status_keywords.csv"
status_keywords_file.negative = "../../../data/health_status_keywords_negative.csv"
status_keywords_file.positive = "../../../data/health_status_keywords_positive.csv"
status_keywords_file.neutral = "../../../data/health_status_keywords_neutral.csv"

output_health_status_file = "../../../../riam/OPG_Demos/output_health_status.csv"
output_causal_effect_file = "../../../../riam/OPG_Demos/output_causal_effect.csv"
abbreviation_file = "../../../data/abbreviations.xlsx"
alias_file = "../../../../riam/OPG_Demos/alias.csv"


[params]
ent_label = "cws_component"
ent_id = "OPM"
