
[files]
cause_effect_keywords_file = "../../../data/cause_effect_keywords.csv"
conjecture_keywords_file = "../../../data/conjecture_keywords.csv"

status_keywords_file.all = "../../../data/health_status_keywords.csv"
status_keywords_file.negative = "../../../data/health_status_keywords_negative.csv"
status_keywords_file.positive = "../../../data/health_status_keywords_positive.csv"
status_keywords_file.neutral = "../../../data/health_status_keywords_neutral.csv"

abbreviation_file = "../../../data/abbreviations.xlsx"
location_file = "../../../data/location_keywords.csv"
time_keywords_file = "../../../data/time_keywords.csv"
time_relation_file = "../../../data/time_relation_keywords.csv"
alias_file = "../../../data/alias.csv"



