[nlp]
language_model = "en_core_web_lg"
logger = "dackar.log"

[nlp.ent]
label = "cws_component"
id = "OPM"

[nlp.files]
text = "../data/nlp_tests.txt"
entity = "../data/entities.csv"
opm = "../opm_models/cws.html"

[nlp.processing]
# normalize
bullet_points = true
hyphenated_words = true
quotation_marks = true
whitespace = true
numerize = true
# remove
brackets = true
html_tags = true
punctuation = ["*","+",":","=","\\","^","_","|","~", "..", "..."]
# replace
currency_symbols = true
emails = true
emojis = true
hashtags = true
numbers = true
phone_numbers = true
urls = true
user_handles = true

[nlp.causal]
type = 'osl' # other options: general: "rule based method", wo: "work order", osl: "operator shift log"

[nlp.analysis]
type = 'causal' # other options: 'ner': 'named entity recognition', 'causal': 'rule based causal analysis'



