[params]
language_model = "en_core_web_lg"
logger = "dackar.log"

[params.ent]
label = "cws_component"
id = "OPM"

[files]
text = "../data/nlp_tests.txt"
entity = "../data/entities.csv"
opm = "../opm_models/cws.html"

[processing]

[processing.normalize]
bullet_points = true
hyphenated_words = true
quotation_marks = true
# repeating_chars = true # need to provide options
# unicode = true
whitespace = true
numerize = true

[processing.remove]
# accents = true
brackets = true
html_tags = true
punctuation = ["*","+",":","=","\\","^","_","|","~", "..", "..."]

[processing.replace]
currency_symbols = true
emails = true
emojis = true
hashtags = true
numbers = true
phone_numbers = true
urls = true
user_handles = true

[causal]
type = 'wo' # other options: general: "rule based method", wo: "work order", osl: "operator shift log"

[analysis]
type = 'causal' # other options: 'ner': 'named entity recognition', 'causal': 'rule based causal analysis', 'similarity', 'anomaly', 'knowledge graph'



