[neo4j]
uri = "neo4j://localhost:7687"
pwd = "password"
# User need to set the import folder, and all files for nodes and edges are using relative path to the import folder
# config_file_path = ""
# import_folder_path = ""
reset = true

[[neo4j.node]]
file = "test_nodes.csv"
label = "MBSE"
attribute = {'nodeId'='nodeId', 'label'='label', 'ID'='ID', 'type'='type'}

[[neo4j.node]]
file = "test_monit_vars.csv"
label = "monitor_var"
attribute = {'nodeId'='varID'}

[[neo4j.node]]
file = "test_AD.csv"
label = "anomaly_detect"
attribute = {'nodeId'='AD_ID', 'type'='type'}

[[neo4j.node]]
file = "test_anomalies.csv"
label = "anomaly"
attribute = {'nodeId'='anom_ID', 'time_initial'='t_in', 'time_final'='t_fin'}

[[neo4j.edge]]
file = "test_edges.csv"
source_label = "MBSE"
target_label = "MBSE"
label = "MBSE_link"
label_attribute = {'prop'='type'}
source_attribute = {'nodeId'='sourceNodeId'}
target_attribute = {'nodeId'='targetNodeId'}

[[neo4j.edge]]
file = "test_monit_vars.csv"
source_label = "monitor_var"
target_label = "MBSE"
label = "monitoring"
source_attribute = {'nodeId'='varID'}
target_attribute = {'nodeId'='MBSE_ID'}

[[neo4j.edge]]
file = "test_AD.csv"
source_label = "anomaly_detect"
target_label = "monitor_var"
label = "input_from"
source_attribute = {'nodeId'='AD_ID'}
target_attribute = {'nodeId'='var_ID'}

[[neo4j.edge]]
file = "test_anomalies.csv"
source_label = "anomaly"
target_label = "anomaly_detect"
label = "detected_by"
source_attribute = {'nodeId'='anom_ID'}
target_attribute = {'nodeId'='AD_ID'}
