[neo4j]
uri = "neo4j://localhost:7687"
pwd = "123456789"
config_file_path = "/Users/wangc/Library/Application Support/Neo4j Desktop/Application/relate-data/dbmss/dbms-28cea4a5-ad08-4fed-94a1-70d44e297586/conf/neo4j.conf"
import_folder_path = "/Users/wangc/projects/DACKAR/examples/KG_demo/"
reset = true

[[neo4j.node]]
file = "../examples/KG_demo/test_nodes.csv"
label = "MBSE"
attribute = {'nodeId'='nodeId', 'label'='label', 'ID'='ID', 'type'='type'}

[[neo4j.node]]
file = "../examples/KG_demo/test_monit_vars.csv"
label = "monitor_var"
attribute = {'nodeId'='varID'}

[[neo4j.node]]
file = "../examples/KG_demo/test_AD.csv"
label = "anomaly_detect"
attribute = {'nodeId'='AD_ID', 'type'='type'}

[[neo4j.node]]
file = "../examples/KG_demo/test_anomalies.csv"
label = "anomaly"
attribute = {'nodeId'='anom_ID', 'time_initial'='t_in', 'time_final'='t_fin'}

[[neo4j.edge]]
file = "../examples/KG_demo/test_edges.csv"
source_label = "MBSE"
target_label = "MBSE"
label = "MBSE_link"
label_attribute = {'prop'='type'}
source_attribute = {'nodeId'='sourceNodeId'}
target_attribute = {'nodeId'='targetNodeId'}

[[neo4j.edge]]
file = "../examples/KG_demo/test_monit_vars.csv"
source_label = "monitor_var"
target_label = "MBSE"
label = "monitoring"
source_attribute = {'nodeId'='varID'}
target_attribute = {'nodeId'='MBSE_ID'}

[[neo4j.edge]]
file = "../examples/KG_demo/test_AD.csv"
source_label = "anomaly_detect"
target_label = "monitor_var"
label = "input_from"
source_attribute = {'nodeId'='AD_ID'}
target_attribute = {'nodeId'='var_ID'}

[[neo4j.edge]]
file = "../examples/KG_demo/test_anomalies.csv"
source_label = "anomaly"
target_label = "anomaly_detect"
label = "detected_by"
source_attribute = {'nodeId'='anom_ID'}
target_attribute = {'nodeId'='AD_ID'}
