[params]
language_model = "en_core_web_lg"
logger = "dackar.log"

[params.ent]
label = "cws_component"
id = "OPM"

[files]
text = "../data/cws_data.txt"
entity = "../data/entities.csv"
opm = "../opm_models/cws.html"

[processing]

[processing.normalize]
bullet_points = true
hyphenated_words = true
quotation_marks = true
repeating_chars = true
unicode = true
whitespace = true

[processing.remove]
accents = true
brackets = true
html_tags = true
punctuation = ["*","+",":","=","\\","^","_","|","~", "..", "..."]

[processing.replace]
currency_symbols = true
emails = true
emojis = true
hashtags = true
numbers = true
phone_numbers = true
urls = true
user_handles = true

processing.numerize = true


[pipelines]
general_ner = true
unit_ner = true
temporal_relation_ner = true
temporal_ner = true
temporal_attribute_ner = true
location_ner = true
emergent_activity_ner = true
conjecture_ner = true


# [Analysis]
# work_order = true
# shift_log = true


