"""
test_robustness_ouc3_ccf.py — Tier 2 Scenario correctness: Common-Cause Failure (CCF) vs. Independent

OUC-3  Common-cause failure vs. independent component failures (Category C vs. A)

Scenario
--------
Two redundant pumps (Train A and Train B) experience the same bearing failure mode
within 18 hours. A shared lubrication skid (LUB-01) serves both trains. The lube-oil
pressure on LUB-01 began decaying 22 hours before Train A's trip.

  Component                Category  Timing                      Allen      Severity
  -----------------------  --------  --------------------------  ---------  --------
  Shared lube skid LUB-01  C (CCF)   lube decay starts 22h pre   OVERLAPS   0.68
  Train A pump bearing     A         vibration 3h pre            OVERLAPS   0.72
  Train B pump bearing     A         vibration 18h pre (prior)   FOLLOWS    0.70

KG topology: U1-LUBE-SKID-01 --[connected_support]--> U1-PUMP-TRAINA-BEARING
             U1-LUBE-SKID-01 --[connected_support]--> U1-PUMP-TRAINB-BEARING
PM compliance: lube oil change on shared skid overdue by 34 days (failed check).

Ground truth
------------
  - Category C (CCF) candidate is generated and retained (CCF logic fires)
  - Category C composite score > Category A composite score (CCF candidate ranks #1)
  - Category C CCF score >= 0.40 (meaningful CCF score from shared dependency + governance)
  - CCF confidence is "medium" or higher (ccf_score >= 0.45 with governance boost)
  - common_cause_summary shows at least 1 candidate with CCF structure detected

Implementation notes
--------------------
  The `common_cause_summary.suspected_common_cause` flag requires >= 2 candidates with
  "medium" confidence AND top_ccf_score >= 0.45. In this fixture, only the Category C
  candidate reaches medium confidence (0.49); the individual Category A candidates
  reach only "low" (0.105) because their CCF-relevant features come only from the
  cluster-aware governance signal, not a direct shared-dependency edge.
  This is correct pipeline behavior: the CCF FM (Category C) is the proper carrier of
  the CCF evidence — asserting suspected_common_cause=True would require either
  operational context (train_oos) or a multi-hop KG path that gives both A candidates
  a direct support_dependency_id.

  This finding is analogous to the OUC-1/OUC-5 discovery that timeline-inconsistent
  candidates land in filtered_out_candidates rather than ruled_out[].

Fixture: tests/fixtures_robustness/ouc3_ccf_vs_independent/
"""

from __future__ import annotations

import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, List
from unittest.mock import MagicMock

import pytest

_RCA_ROOT = Path(__file__).resolve().parents[3] / "src" / "dackar" / "RCA"
_SCENARIO_ROOT = Path(__file__).resolve().parents[1] / "scenario"
_TESTS_SHARED = _SCENARIO_ROOT / "shared"
_FIXTURE_DIR = _SCENARIO_ROOT / "fixtures_robustness" / "ouc3_ccf_vs_independent"

for _p in (str(_RCA_ROOT), str(_TESTS_SHARED)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

for _mod in (
    "neo4j", "py2neo", "chromadb",
    "langchain_community", "langchain_community.vectorstores",
    "langchain_community.embeddings",
):
    if _mod not in sys.modules:
        sys.modules[_mod] = MagicMock()

import pytest  # noqa: E402
pytest.importorskip("run_helpers", reason="scenario shared helpers (tests/RCA/scenario/shared) arrive in MR #12")
from run_helpers import build_fixture_orchestrator, load_fixtures, run_rca  # noqa: E402


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _run() -> Dict[str, Any]:
    fixtures = load_fixtures(_FIXTURE_DIR)
    with tempfile.TemporaryDirectory() as tmp:
        orch = build_fixture_orchestrator(tmp)
        return run_rca(orch, fixtures)


def _retained(result: Dict[str, Any]) -> List[Dict[str, Any]]:
    return result["causality_candidates"].get("candidates") or []


def _all_cands(result: Dict[str, Any]) -> List[Dict[str, Any]]:
    cc = result["causality_candidates"]
    return (cc.get("candidates") or []) + (cc.get("filtered_out_candidates") or [])


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

def test_ouc3_category_c_generated():
    """OUC-3: A Category C (CCF) candidate must be generated by the engine."""
    result = _run()
    all_cands = _all_cands(result)
    c_cands = [c for c in all_cands if c.get("primary_causal_category") == "C"]
    assert c_cands, (
        "OUC-3: No Category C candidate generated at all. "
        "Ensure the KG has a failure mode with causal_category='C' and the connected_support "
        "edges link U1-LUBE-SKID-01 to both train bearing components."
    )


def test_ouc3_category_c_retained():
    """OUC-3: Category C candidate must be retained (not filtered out)."""
    result = _run()
    retained = _retained(result)
    c_cats = {c["primary_causal_category"] for c in retained}
    assert "C" in c_cats, (
        "OUC-3: Category C candidate was generated but filtered out. "
        "Check that evidence_bundle.candidate_evidence_summary covers FM-OUC3-CCF-LUBE-LOT "
        "with best_support_score >= minimum_evidence_threshold."
    )


def test_ouc3_c_ranks_above_a():
    """OUC-3: Category C composite score must exceed the best Category A composite score."""
    result = _run()
    retained = _retained(result)
    c_scores = [c["composite_score"] for c in retained if c["primary_causal_category"] == "C"]
    a_scores = [c["composite_score"] for c in retained if c["primary_causal_category"] == "A"]
    assert c_scores, "OUC-3: No Category C retained candidate"
    assert a_scores, "OUC-3: No Category A retained candidate"
    assert max(c_scores) > max(a_scores), (
        f"OUC-3: Category C best composite={max(c_scores):.4f} should exceed "
        f"Category A best composite={max(a_scores):.4f}. "
        "The CCF (shared lubrication) candidate should rank above independent bearing FMs "
        "when multi-train occurrence, upstream dependency, and strong evidence all point "
        "to the shared support system."
    )


def test_ouc3_c_ranked_first():
    """OUC-3: Category C candidate must occupy the top rank in the retained list."""
    result = _run()
    retained = _retained(result)
    assert retained, "OUC-3: No candidates retained"
    assert retained[0]["primary_causal_category"] == "C", (
        f"OUC-3: Top candidate is Category {retained[0]['primary_causal_category']!r} "
        f"({retained[0]['component_id']}), expected Category C (shared lube skid). "
        "Common-cause failure hypotheses must rank first when the shared-dependency topology "
        "and multi-train evidence strongly support them."
    )


def test_ouc3_ccf_score_meaningful():
    """OUC-3: Category C candidate must carry a meaningful CCF score (>= 0.40)."""
    result = _run()
    retained = _retained(result)
    c_cand = next((c for c in retained if c["primary_causal_category"] == "C"), None)
    assert c_cand is not None, "OUC-3: No Category C retained"
    ccf_score = (c_cand.get("scores") or {}).get("ccf_score", 0.0)
    assert ccf_score >= 0.40, (
        f"OUC-3: CCF candidate ccf_score={ccf_score:.4f} < 0.40. "
        "Shared lube skid connected_support edges + failed PM check should yield "
        "shared_dependency_signal=1.0 + governance_commonality_signal=0.5."
    )


def test_ouc3_ccf_confidence_medium_or_high():
    """OUC-3: Category C CCF candidate must reach at least 'medium' confidence."""
    result = _run()
    retained = _retained(result)
    c_cand = next((c for c in retained if c["primary_causal_category"] == "C"), None)
    assert c_cand is not None, "OUC-3: No Category C retained"
    ccf_inner = c_cand.get("common_cause") or {}
    confidence = ccf_inner.get("common_cause_confidence", "none")
    assert confidence in {"medium", "high"}, (
        f"OUC-3: CCF candidate common_cause_confidence={confidence!r}; "
        "expected 'medium' or 'high'. pm_compliance failed check + shared dependency edge "
        "should push governance_commonality_signal=0.5 → ccf_score >= 0.45 → 'medium'."
    )


def test_ouc3_ccf_structure_detected_in_summary():
    """OUC-3: common_cause_summary must show at least one CCF-bearing candidate."""
    result = _run()
    cc_summary = (result["causality_candidates"].get("common_cause_summary") or {})
    count = cc_summary.get("candidate_count_with_common_cause", 0)
    assert count >= 1, (
        f"OUC-3: common_cause_summary.candidate_count_with_common_cause={count}; "
        "expected >= 1. The engine must record CCF structure even if suspected_common_cause "
        "does not fire."
    )


# ---------------------------------------------------------------------------
# Test registry
# ---------------------------------------------------------------------------

ALL_TESTS = [
    test_ouc3_category_c_generated,
    test_ouc3_category_c_retained,
    test_ouc3_c_ranks_above_a,
    test_ouc3_c_ranked_first,
    test_ouc3_ccf_score_meaningful,
    test_ouc3_ccf_confidence_medium_or_high,
    test_ouc3_ccf_structure_detected_in_summary,
]

if __name__ == "__main__":
    for fn in ALL_TESTS:
        try:
            fn()
            print(f"  PASS  {fn.__name__}")
        except AssertionError as e:
            print(f"  FAIL  {fn.__name__}: {e}")
        except Exception as e:
            print(f"  ERROR {fn.__name__}: {e}")
