"""
demo_data.py — Externalized data for the outage_uncertainty_demo notebook.

Plant Millbrook · Refuelling Outage OH-005 (fictional PWR)

Importing this module gives you:
    OUTAGE_METADATA       — dict with outage header fields
    HISTORICAL_ROWS       — list[dict], 35 completed activities from 3 prior outages
    PLANNED_ACTIVITIES    — list[dict], 6 planned activities for OH-005
    SCHEDULE_TOPOLOGY     — list of tuples for building the ScheduleNetwork
    BENCHMARK_CSV         — pathlib.Path to the pre-processing benchmark CSV
    BENCHMARK_SEV_CSV     — pathlib.Path to the severity-annotated benchmark CSV
"""
from __future__ import annotations

from pathlib import Path

# ---------------------------------------------------------------------------
# File paths
# ---------------------------------------------------------------------------

_DEMO_DIR = Path(__file__).resolve().parent
BENCHMARK_CSV = (
    _DEMO_DIR.parent / "unexpected_act_workflow_1" / "outage_cleaning_benchmark.csv"
)
BENCHMARK_SEV_CSV = (
    _DEMO_DIR.parent
    / "unexpected_act_workflow_1"
    / "outage_cleaning_benchmark_severity.csv"
)

# ---------------------------------------------------------------------------
# Outage header
# ---------------------------------------------------------------------------

OUTAGE_METADATA: dict = {
    "outage_id":      "OH-005",
    "plant_id":       "Millbrook-U2",
    "unit_id":        "U2",
    "outage_name":    "OH-005 Spring Refuelling Outage",
    "start_planned":  "2025-04-01T00:00:00",
    "finish_planned": "2025-04-22T00:00:00",   # 504 h planned (21 days)
}

# ---------------------------------------------------------------------------
# Historical database — 35 completed activities across 3 prior outages
# ---------------------------------------------------------------------------

HISTORICAL_ROWS: list[dict] = [
    # ── OH-001  2022 Unit 1 ──────────────────────────────────────────────────
    {"activity_id": "H001", "outage_id": "OH-001", "plant_id": "Millbrook-U1",
     "raw_description": "Main coolant pump MCP-1A mechanical seal replacement",
     "discipline": "mechanical", "task_family": "replacement",
     "component_family": "pump",
     "planned_duration_hours": 20.0, "actual_duration_hours": 23.5,
     "has_rp_hold": True, "outage_phase": "planned outage"},
    {"activity_id": "H002", "outage_id": "OH-001", "plant_id": "Millbrook-U1",
     "raw_description": "RHR pump 1A discharge valve packing replacement",
     "discipline": "mechanical", "task_family": "replacement",
     "component_family": "valve",
     "planned_duration_hours": 6.0, "actual_duration_hours": 7.5,
     "outage_phase": "planned outage"},
    {"activity_id": "H003", "outage_id": "OH-001", "plant_id": "Millbrook-U1",
     "raw_description": "MSIV valve stem inspection unit 1 A train",
     "discipline": "mechanical", "task_family": "inspection",
     "component_family": "valve",
     "planned_duration_hours": 10.0, "actual_duration_hours": 11.0,
     "outage_phase": "planned outage"},
    {"activity_id": "H004", "outage_id": "OH-001", "plant_id": "Millbrook-U1",
     "raw_description": "Charging pump 1B complete overhaul impeller and bearings",
     "discipline": "mechanical", "task_family": "refurbishment",
     "component_family": "pump",
     "planned_duration_hours": 40.0, "actual_duration_hours": 47.0,
     "outage_phase": "planned outage"},
    {"activity_id": "H005", "outage_id": "OH-001", "plant_id": "Millbrook-U1",
     "raw_description": "Level transmitter LT-101 channel calibration loop check",
     "discipline": "I&C", "task_family": "calibration",
     "component_family": "instrument",
     "planned_duration_hours": 3.0, "actual_duration_hours": 3.0,
     "outage_phase": "planned outage"},
    {"activity_id": "H006", "outage_id": "OH-001", "plant_id": "Millbrook-U1",
     "raw_description": "Flow transmitter FT-203 calibration set point verification",
     "discipline": "I&C", "task_family": "calibration",
     "component_family": "instrument",
     "planned_duration_hours": 3.0, "actual_duration_hours": 4.0,
     "outage_phase": "planned outage"},
    {"activity_id": "H007", "outage_id": "OH-001", "plant_id": "Millbrook-U1",
     "raw_description": "ECCS injection valve MOV actuator replacement",
     "discipline": "mechanical", "task_family": "replacement",
     "component_family": "valve",
     "planned_duration_hours": 24.0, "actual_duration_hours": 38.0,
     "has_rp_hold": True, "has_clearance": True, "outage_phase": "planned outage"},
    {"activity_id": "H008", "outage_id": "OH-001", "plant_id": "Millbrook-U1",
     "raw_description": "Main transformer A bushing inspection and oil sampling",
     "discipline": "electrical", "task_family": "inspection",
     "component_family": "transformer",
     "planned_duration_hours": 6.0, "actual_duration_hours": 6.0,
     "outage_phase": "planned outage"},
    {"activity_id": "H009", "outage_id": "OH-001", "plant_id": "Millbrook-U1",
     "raw_description": "Bus 2A medium voltage breaker preventive maintenance",
     "discipline": "electrical", "task_family": "maintenance",
     "component_family": "breaker",
     "planned_duration_hours": 4.0, "actual_duration_hours": 4.5,
     "outage_phase": "planned outage"},
    {"activity_id": "H010", "outage_id": "OH-001", "plant_id": "Millbrook-U1",
     "raw_description": "Condenser tube bundle cleaning and inspection",
     "discipline": "mechanical", "task_family": "cleaning",
     "component_family": "condenser",
     "planned_duration_hours": 12.0, "actual_duration_hours": 14.0,
     "outage_phase": "planned outage"},
    # ── OH-002  2023 Unit 1 ──────────────────────────────────────────────────
    {"activity_id": "H011", "outage_id": "OH-002", "plant_id": "Millbrook-U1",
     "raw_description": "Main coolant pump MCP-1B mechanical seal replacement",
     "discipline": "mechanical", "task_family": "replacement",
     "component_family": "pump",
     "planned_duration_hours": 20.0, "actual_duration_hours": 26.0,
     "has_rp_hold": True, "outage_phase": "planned outage"},
    {"activity_id": "H012", "outage_id": "OH-002", "plant_id": "Millbrook-U1",
     "raw_description": "RHR pump 1B suction valve packing replacement",
     "discipline": "mechanical", "task_family": "replacement",
     "component_family": "valve",
     "planned_duration_hours": 6.0, "actual_duration_hours": 6.5,
     "outage_phase": "planned outage"},
    {"activity_id": "H013", "outage_id": "OH-002", "plant_id": "Millbrook-U1",
     "raw_description": "MSIV valve B train full inspection disassembly",
     "discipline": "mechanical", "task_family": "inspection",
     "component_family": "valve",
     "planned_duration_hours": 10.0, "actual_duration_hours": 13.5,
     "outage_phase": "planned outage"},
    {"activity_id": "H014", "outage_id": "OH-002", "plant_id": "Millbrook-U1",
     "raw_description": "Charging pump 1A overhaul casing and mechanical seal",
     "discipline": "mechanical", "task_family": "refurbishment",
     "component_family": "pump",
     "planned_duration_hours": 40.0, "actual_duration_hours": 53.0,
     "outage_phase": "planned outage"},
    {"activity_id": "H015", "outage_id": "OH-002", "plant_id": "Millbrook-U1",
     "raw_description": "Pressure transmitter PT-305 calibration set point",
     "discipline": "I&C", "task_family": "calibration",
     "component_family": "instrument",
     "planned_duration_hours": 3.0, "actual_duration_hours": 3.0,
     "outage_phase": "planned outage"},
    {"activity_id": "H016", "outage_id": "OH-002", "plant_id": "Millbrook-U1",
     "raw_description": "Temperature element TE-401 replacement loop verification",
     "discipline": "I&C", "task_family": "replacement",
     "component_family": "instrument",
     "planned_duration_hours": 4.0, "actual_duration_hours": 5.5,
     "outage_phase": "planned outage"},
    {"activity_id": "H017", "outage_id": "OH-002", "plant_id": "Millbrook-U1",
     "raw_description": "HPSI pump 1A mechanical seal and bearing overhaul",
     "discipline": "mechanical", "task_family": "refurbishment",
     "component_family": "pump",
     "planned_duration_hours": 32.0, "actual_duration_hours": 35.0,
     "has_rp_hold": True, "outage_phase": "planned outage"},
    {"activity_id": "H018", "outage_id": "OH-002", "plant_id": "Millbrook-U1",
     "raw_description": "EDG emergency diesel generator fuel oil system maintenance",
     "discipline": "mechanical", "task_family": "maintenance",
     "component_family": "generator",
     "planned_duration_hours": 16.0, "actual_duration_hours": 16.0,
     "outage_phase": "planned outage"},
    {"activity_id": "H019", "outage_id": "OH-002", "plant_id": "Millbrook-U1",
     "raw_description": "CCW heat exchanger tube side cleaning and inspection",
     "discipline": "mechanical", "task_family": "cleaning",
     "component_family": "heat exchanger",
     "planned_duration_hours": 10.0, "actual_duration_hours": 12.0,
     "outage_phase": "planned outage"},
    {"activity_id": "H020", "outage_id": "OH-002", "plant_id": "Millbrook-U1",
     "raw_description": "Switchgear bus A annual preventive maintenance",
     "discipline": "electrical", "task_family": "maintenance",
     "component_family": "switchgear",
     "planned_duration_hours": 6.0, "actual_duration_hours": 6.5,
     "outage_phase": "planned outage"},
    # ── OH-003  2024 Unit 2 ──────────────────────────────────────────────────
    {"activity_id": "H021", "outage_id": "OH-003", "plant_id": "Millbrook-U2",
     "raw_description": "Main coolant pump MCP-2A mechanical seal complete replacement",
     "discipline": "mechanical", "task_family": "replacement",
     "component_family": "pump",
     "planned_duration_hours": 20.0, "actual_duration_hours": 22.0,
     "has_rp_hold": True, "outage_phase": "planned outage"},
    {"activity_id": "H022", "outage_id": "OH-003", "plant_id": "Millbrook-U2",
     "raw_description": "Pressurizer heater replacement bundle 2A",
     "discipline": "electrical", "task_family": "replacement",
     "component_family": "heater",
     "planned_duration_hours": 14.0, "actual_duration_hours": 18.0,
     "outage_phase": "planned outage"},
    {"activity_id": "H023", "outage_id": "OH-003", "plant_id": "Millbrook-U2",
     "raw_description": "MSIV valve A unit 2 full disassembly inspection and reassembly",
     "discipline": "mechanical", "task_family": "inspection",
     "component_family": "valve",
     "planned_duration_hours": 10.0, "actual_duration_hours": 10.0,
     "outage_phase": "planned outage"},
    {"activity_id": "H024", "outage_id": "OH-003", "plant_id": "Millbrook-U2",
     "raw_description": "Charging pump 2B overhaul impeller bearings casing",
     "discipline": "mechanical", "task_family": "refurbishment",
     "component_family": "pump",
     "planned_duration_hours": 40.0, "actual_duration_hours": 44.0,
     "outage_phase": "planned outage"},
    {"activity_id": "H025", "outage_id": "OH-003", "plant_id": "Millbrook-U2",
     "raw_description": "Differential pressure transmitter DP-201 calibration",
     "discipline": "I&C", "task_family": "calibration",
     "component_family": "instrument",
     "planned_duration_hours": 3.0, "actual_duration_hours": 3.5,
     "outage_phase": "planned outage"},
    {"activity_id": "H026", "outage_id": "OH-003", "plant_id": "Millbrook-U2",
     "raw_description": "Safety injection pump 2B mechanical seal replacement",
     "discipline": "mechanical", "task_family": "replacement",
     "component_family": "pump",
     "planned_duration_hours": 18.0, "actual_duration_hours": 21.0,
     "has_rp_hold": True, "outage_phase": "planned outage"},
    {"activity_id": "H027", "outage_id": "OH-003", "plant_id": "Millbrook-U2",
     "raw_description": "RHR heat exchanger tube bundle inspection eddy current",
     "discipline": "mechanical", "task_family": "inspection",
     "component_family": "heat exchanger",
     "planned_duration_hours": 24.0, "actual_duration_hours": 28.0,
     "outage_phase": "planned outage"},
    {"activity_id": "H028", "outage_id": "OH-003", "plant_id": "Millbrook-U2",
     "raw_description": "Bus 4B medium voltage breaker overhaul and testing",
     "discipline": "electrical", "task_family": "refurbishment",
     "component_family": "breaker",
     "planned_duration_hours": 8.0, "actual_duration_hours": 9.5,
     "outage_phase": "planned outage"},
    {"activity_id": "H029", "outage_id": "OH-003", "plant_id": "Millbrook-U2",
     "raw_description": "Service water pump SWP-2A bearing replacement",
     "discipline": "mechanical", "task_family": "replacement",
     "component_family": "pump",
     "planned_duration_hours": 8.0, "actual_duration_hours": 9.0,
     "outage_phase": "planned outage"},
    {"activity_id": "H030", "outage_id": "OH-003", "plant_id": "Millbrook-U2",
     "raw_description": "Main feedwater regulating valve actuator replacement",
     "discipline": "mechanical", "task_family": "replacement",
     "component_family": "valve",
     "planned_duration_hours": 16.0, "actual_duration_hours": 19.0,
     "outage_phase": "planned outage"},
    {"activity_id": "H031", "outage_id": "OH-003", "plant_id": "Millbrook-U2",
     "raw_description": "Containment spray pump CSP-2A mechanical seal overhaul",
     "discipline": "mechanical", "task_family": "refurbishment",
     "component_family": "pump",
     "planned_duration_hours": 20.0, "actual_duration_hours": 24.0,
     "has_rp_hold": True, "outage_phase": "planned outage"},
    {"activity_id": "H032", "outage_id": "OH-003", "plant_id": "Millbrook-U2",
     "raw_description": "Moisture separator reheater MSR inspection and tube plugging",
     "discipline": "mechanical", "task_family": "inspection",
     "component_family": "heat exchanger",
     "planned_duration_hours": 30.0, "actual_duration_hours": 36.0,
     "outage_phase": "planned outage"},
    {"activity_id": "H033", "outage_id": "OH-003", "plant_id": "Millbrook-U2",
     "raw_description": "125V DC battery charger replacement unit 2A",
     "discipline": "electrical", "task_family": "replacement",
     "component_family": "battery",
     "planned_duration_hours": 6.0, "actual_duration_hours": 7.0,
     "outage_phase": "planned outage"},
    {"activity_id": "H034", "outage_id": "OH-003", "plant_id": "Millbrook-U2",
     "raw_description": "CRD mechanism housing weld inspection ultrasonic",
     "discipline": "mechanical", "task_family": "inspection",
     "component_family": "crd",
     "planned_duration_hours": 48.0, "actual_duration_hours": 52.0,
     "has_rp_hold": True, "outage_phase": "planned outage"},
    {"activity_id": "H035", "outage_id": "OH-003", "plant_id": "Millbrook-U2",
     "raw_description": "Turbine governor valve GV-1 overhaul and stroke test",
     "discipline": "mechanical", "task_family": "refurbishment",
     "component_family": "valve",
     "planned_duration_hours": 24.0, "actual_duration_hours": 27.0,
     "outage_phase": "planned outage"},
]

# ---------------------------------------------------------------------------
# Planned activities — OH-005 (6 work packages)
# ---------------------------------------------------------------------------

PLANNED_ACTIVITIES: list[dict] = [
    {"activity_id": "Q-MCP-2B",    "outage_id": "OH-005", "plant_id": "Millbrook-U2",
     "raw_description": "MCP-2B mechanical seal and bearing replacement",
     "discipline": "mechanical", "component_family": "pump",
     "planned_duration_hours": 20.0, "has_rp_hold": True,
     "outage_phase": "planned outage"},
    {"activity_id": "Q-MSIV-2",    "outage_id": "OH-005", "plant_id": "Millbrook-U2",
     "raw_description": "MSIV valve unit 2 full disassembly and inspection",
     "discipline": "mechanical", "component_family": "valve",
     "planned_duration_hours": 10.0,
     "outage_phase": "planned outage"},
    {"activity_id": "Q-LT-CALIB",  "outage_id": "OH-005", "plant_id": "Millbrook-U2",
     "raw_description": "Level transmitter LT-220 calibration and loop check",
     "discipline": "I&C", "component_family": "instrument",
     "planned_duration_hours": 3.0,
     "outage_phase": "planned outage"},
    {"activity_id": "Q-HX-CCW",    "outage_id": "OH-005", "plant_id": "Millbrook-U2",
     "raw_description": "CCW heat exchanger tube side inspection and cleaning",
     "discipline": "mechanical", "component_family": "heat exchanger",
     "planned_duration_hours": 10.0,
     "outage_phase": "planned outage"},
    {"activity_id": "Q-BKR-4A",    "outage_id": "OH-005", "plant_id": "Millbrook-U2",
     "raw_description": "Bus 4A medium voltage breaker overhaul",
     "discipline": "electrical", "component_family": "breaker",
     "planned_duration_hours": 8.0,
     "outage_phase": "planned outage"},
    {"activity_id": "Q-DCS-UPGRDE","outage_id": "OH-005", "plant_id": "Millbrook-U2",
     "raw_description": "DCS digital control system upgrade and functional test",
     "discipline": "I&C", "component_family": "controller",
     "planned_duration_hours": 40.0,
     "outage_phase": "planned outage"},
]

# ---------------------------------------------------------------------------
# Schedule topology — 9-node network for OH-005
# Each entry: (activity_id, display_name, predecessors, successors, baseline_h)
# ---------------------------------------------------------------------------

SCHEDULE_TOPOLOGY: list[tuple] = [
    ("Q-INIT",       "Outage start / tag-outs",
     [], ["Q-MCP-2B", "Q-MSIV-2", "Q-HX-CCW", "Q-DCS-UPGRDE"], 4.0),
    ("Q-MCP-2B",     "MCP-2B seal replacement",
     ["Q-INIT"], ["Q-REPL"], 20.0),
    ("Q-MSIV-2",     "MSIV unit 2 inspection",
     ["Q-INIT"], ["Q-END"], 10.0),
    ("Q-HX-CCW",     "CCW HX clean & inspect",
     ["Q-INIT"], ["Q-LT-CALIB"], 10.0),
    ("Q-LT-CALIB",   "LT-220 calibration",
     ["Q-HX-CCW"], ["Q-BKR-4A"], 3.0),
    ("Q-BKR-4A",     "Bus 4A breaker overhaul",
     ["Q-LT-CALIB"], ["Q-END"], 8.0),
    ("Q-DCS-UPGRDE", "DCS upgrade & functional test",
     ["Q-INIT"], ["Q-END"], 40.0),
    ("Q-REPL",       "Reactor plant re-entry checks",
     ["Q-MCP-2B"], ["Q-END"], 6.0),
    ("Q-END",        "Outage end / restart",
     ["Q-REPL", "Q-MSIV-2", "Q-BKR-4A", "Q-DCS-UPGRDE"], [], 2.0),
]
