name: "Sphinx: Render docs"

on: push

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install
      - name: Install docs dependencies
        run: uv sync --group docs
      # - name: Use Pandoc
      #   uses: docker://pandoc/core:2.9
      #   with:
      #     args: "--help" # gets appended to pandoc command
      - name: Install
        uses: pandoc/actions/setup@v1
        with:
          version: 2.19

      - name: Run pandoc
        run: pandoc --version
      - run: echo " Install Libraries Required to build Sphinx Documents"
      - run: |
          pwd
          ls -l
          cd docs
          uv run make html
          cd ..
      # - name: Build HTML
      #   uses: ammaraskar/sphinx-action@master
      #   with:
      #     pre-build-command: "apt-get update && apt-get install -y pandoc"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/_build/html/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
